### ISSUE TITLE
新需求：文字还原

### ISSUE THREAD

**Issue by DeqianBai** [pengzhendong/text_normalization#1]
把出现的半缩写还原成文字：

100的j格对比它的妆效—>100的价格对比它的妆效
皮肤易m感—>皮肤易敏感

**Comment by pengzhendong** [comment]
将 `j格\t价格` 添加到白名单 `data/default/whitelist.txt` 中即可实现替换。

参考 `O2O` 和 `O to O`。

**Comment by pengzhendong** [comment]
这些半缩写词语不太统一，不考虑添加到项目中，使用者可针对性添加。
