### ISSUE TITLE
Ethical issue

### ISSUE THREAD

**Issue by dophist** [pengzhendong/text_normalization#3]
For whatever reason, it seems you choose to fork the work from Zhenxiang(undergraduate intern at SpeechColab) rather than improving the code directly in Nemo, this is OK.  But erasing SpeechColab from `credits` section and avoid mentioning the original work in Nemo project is not an ethical act for open-source projects.

**Comment by pengzhendong** [comment]
Deleted by mistake, recovered.

**Comment by dophist** [comment]
You can just put SpeechColab organization/authors into the acknowledgement list at the end, since SpeechColab is not giving advices to this fork directly. 

I'm closing this anyway, thanks.

**Comment by pengzhendong** [comment]
Thanks for your advices.

https://github.com/pengzhendong/text_normalization/commit/60a71c0a7367df89c5d6e0cc832804a6ca58e714
